
// Objective-C API for talking to the following Go packages
//
//	pkg/nymble
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Nymble_FRAMEWORK_H__
#define __Nymble_FRAMEWORK_H__

#include "Nymble.objc.h"
#include "Universe.objc.h"

#endif
