
// Objective-C API for talking to the following Go packages
//
//	pkg/pkg
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Pkg_FRAMEWORK_H__
#define __Pkg_FRAMEWORK_H__

#include "Pkg.objc.h"
#include "Universe.objc.h"

#endif
